setting:
  CPU_Console:
    port: ""           #eg. /dev/ttyUSB2
    Username: "root"
    Password: "admin@123"

  CPU_ssh:
    Ip_address: "10.196.197.88"
    Username: "root"
    Password: "admin@123"
    Host_Prompt: ".*#"

  BMC_Console:
    port: ""           #eg. /dev/ttyUSB1
    Username: "root"
    Password: "0penBmc"

  BMC_ssh:
    Ip_address: ""
    Username: "root"
    Password: "0penBmc"
    Host_Prompt: ".*#"

  # For telnet based console access of remote target.
  # It can be used for accessing BMC concsole over telnet, such as for mac test.
  # For this feature to work correctly, Change connection_type to 'BMC_telnet' 
  # and list IP address and port number of telnet host below.
  BMC_telnet:
    Ip_address: ""  # e.g 192.168.10.90
    Port: ""        # e.g 2001
    Username: "root"
    Password: "0penBmc"

  # The user must specify which component (CPU,BMC) and which conenction to use for each modules in the below list
  # Can be any one of
  # 1. CPU_Console
  # 2. CPU_ssh
  # 3. BMC_Console
  # 4. BMC_ssh
  # 5. direct (running on same machine)
  # 6. CPU_SOL_Console (running on CPU console using BMC SOL)
  # 7. CPU_USB_SSH (running on CPU ssh from BMC ssh using the USB interface from BMC)
  # All_CPU_connection: 'CPU_Console/ CPU_ssh/ direct/ CPU_SOL_Console/ CPU_USB_SSH' can be used.
  # All_BMC_connection: 'BMC_ssh/ BMC_Console' can be used.
  connection_type:
    # Compute Testcases. by default All_CPU_connection type are supported
    bios: CPU_USB_SSH
    secureboot : CPU_USB_SSH
    sensor_cpu: CPU_USB_SSH
    mem : CPU_USB_SSH
    tpm : CPU_USB_SSH
    rtc : CPU_USB_SSH
    dmesg : CPU_USB_SSH
    version : CPU_USB_SSH
    ssd : CPU_USB_SSH
    nic_400g : CPU_USB_SSH
    ras : CPU_USB_SSH
    nvme : CPU_USB_SSH
    i2c : CPU_USB_SSH
    cpu : CPU_USB_SSH
    pcie : CPU_USB_SSH
    pcie_switch: CPU_USB_SSH   # For PCIe commands that use a port method to access the console, BMC_ssh credentials are required.
    cpld : CPU_USB_SSH
    CPU_BMC_TEST: BMC_ssh   # options: BMC_ssh/BMC_Console. This connection type is used for CPU cases where bmc commands needs to be accessed.
    stress : CPU_USB_SSH
    upgrade_cpu: CPU_USB_SSH
    bandwidth : CPU_USB_SSH
    upgrade_pcie_cpu: CPU_USB_SSH # options: CPU_ssh/CPU_USB_SSH
    power_cpu : CPU_USB_SSH
    stv: CPU_ssh
    cdfp: CPU_USB_SSH

    # BMC Testcases. by default All_BMC_connection type are supported.
    dmesg_bmc : BMC_ssh
    eeprom : BMC_ssh
    fan : BMC_ssh
    gpio : BMC_ssh
    i2c_bmc : BMC_ssh
    led : BMC_Console   # option: BMC_Console or BMC_telnet
    mac : BMC_Console   # option: BMC_Console or BMC_telnet
    mdio : BMC_ssh
    power : BMC_ssh
    rtc_bmc : BMC_ssh
    sensor : BMC_ssh
    spi : BMC_ssh
    tpm_bmc : BMC_ssh
    upgrade : BMC_ssh
    version_bmc : BMC_ssh

usb:
    CPU_USB_INTERFACE: "usb0"
    BMC_USB_INTERFACE: "usb0"
    CPU_USB_IP: "169.254.0.1"
    BMC_USB_IP: "169.254.0.17"

uart:
  CPU:
    console: "2200"
  BMC:
    console: "22"
  PCIE_SW1:
    console: "2201"
  PCIE_SW2:
    console: "2202"
  PCIE_SW3:
    console: "2203"
  PCIE_SW4:
    console: "2204"

mac:
  # set BMC lan1 static IP address Testcase
  ip_addr_read_from_cfg: "NO"
  ip_addr: ""    # e.g 192.168.10.90
  netmask: ""    # e.g 255.255.254.0
  # Program BMC MAC address Tesctcase
  mac_addr_read_from_cfg: "NO"
  mac_addr: ""   # e.g AA:BB:CC:DD:EE:FF

# Set this field to NO, and user would not be prompted for eeprom type.
# This can be useful for automation.
# When EEPROM_TYPE_USER_INPUT is set to NO, DEFAULT_EEPROM value is taken as user input substitute
# and would be used by eeprom test handler.
eeprom:
  EEPROM_TYPE_USER_INPUT: "YES"
  DEFAULT_EEPROM: "0"
  UUID_NAMESPACE: "6ba7b815-9dad-11d1-80b4-434c53524007"

# ----- FE NIC and BIOS fw upgrade/downgrade Testcase -----
upgrade_cpu:
  fe_nic:
    current_version: "233.0.152.6"
    reset_sleep_time: 640
    fw_upgrade:
      fw_upgrade_image_path: "/usr/local/fw_images/upgrade_images/BCM957608-P1400GDF00_234_0_145_0.pkg"
      fw_upgrade_version: "234.0.145.0"
    fw_downgrade:
      fw_downgrade_image_path: "/usr/local/fw_images/downgrade_images/BCM957608-P1400GDF00_233_0_152_6.pkg"
      fw_downgrade_version: "233.0.152.6"
  bios:
    bios_update_tool_path: '/usr/local/tools/AfuLnx64/AfuLnx64/afulnx_64'
    cmd_argument_without_rot: "/P /B /N /K /RLC:E"  # If the layout changes, you need to add the parameter /RLC:E
    cmd_argument_rot: "/K"
    current_version: "KAT.1.01.01"
    reset_sleep_time: 600
    fw_upgrade:
      fw_upgrade_image_path: "/usr/local/fw_images/upgrade_images/KAT.1.02.01.FD"   # For PFR .bin image and for Non-PFR .FD image
      fw_upgrade_version: "KAT.1.02.01"
    fw_downgrade:
      fw_downgrade_image_path: "/usr/local/fw_images/downgrade_images/KAT.1.01.01.FD"  # For PFR .bin image and for Non-PFR .FD image
      fw_downgrade_version: "KAT.1.01.01"

# ----- PCIe fw upgrade/downgrade ------
pcie_fw:
  total_pcie_switch: 4
  switchclid_path: '/usr/sbin/switchclid.x86_64'
  current_version: "21.02.03.01"
  reset_after_each_pcie_fw_download: "Yes"    # "Yes" or "No"
  timeout_for_download_pcie_fw: 660
  reset_sleep_time: 300
  fw_upgrade:
    fw_upgrade_image_path: "/usr/local/fw_images/upgrade_images/image.signed_23_02_24_01.fw"
    fw_upgrade_version: "23.02.24.01"
  fw_downgrade:
    fw_downgrade_image_path: "/usr/local/fw_images/downgrade_images/image.signed_21_02_03_01.fw"
    fw_downgrade_version: "21.02.03.01"

PDU_Details: 
    Ip_address: ""    # PDU ip: eg, 10.204.82.18
    Username: ""      # PDU username eg,apc
    Password: ""   # PDU password eg,apc
    Type: "telnet"     # Can be either "telnet" or "ssh"
    Model: ""       # Can be either "" or "wti"
    PSU_off_cmd: ""
    PSU_on_cmd: ""
    PDU_Prompt: ""
    login_prompt: ""    # used if type is telnet
    return_prompt: ""     # Return value after successful command execution
    port: ""                     # Change the type if it is telnet and requires it, e.g., 3207.
    sleep_for_boot_time: "420"   # in seconds

upgrade_bmc:
  cpld:
    current_version: "0.2.0"
    reset_sleep_time: 600
    fw_upgrade:
      fw_upgrade_image_path: "/root/katsu_mb_cpld_v0.3.0_ugd.vme"
      fw_upgrade_version: "0.3.0"
  bios:
    current_version: "KAT.1.01.01"
    reset_sleep_time: 600
    fw_upgrade:
      fw_upgrade_image_path: "/root/KAT.1.02.01.FD"  # For PFR .bin image and for NON-PFR .FD image
      fw_upgrade_version: "KAT.1.02.01"
  pcie:
    total_pcie_switch: 4
    current_version: "21.02.03.01"
    reset_sleep_time: 600
    fw_upgrade:
      fw_upgrade_image_path: "/root/image.signed_23_02_24_01.pex"
      fw_upgrade_version: "23.02.24.01"
  bmc: 
    current_version: "0.4.0"
    reset_sleep_time: 600
    fw_upgrade:
      fw_upgrade_image_path: "/root/obmc-phosphor-image-katsu-20251210150431.static.mtd" # For PFR .bin image and for NON-PFR .mtd image
      fw_upgrade_version: "0.5.0"
  nic_400g:
    current_version: "234.1.124.0"
    reset_sleep_time: 400
    fw_upgrade:
      fw_upgrade_image_path: "/root/BCM957608-P2200GQF00.pldm"
      fw_upgrade_version: "235.1.160.0"
  rot:
    reset_sleep_time: 600
    fw_upgrade:
      fw_upgrade_image_path: "/root/zephyr_signed_katsu_1_0.bin"

# ------------------- Test Compute Version ---------------------
bios:
  BIOS_VERSION: "KAT.1.02.01"
os:
  OS_VERSION :
    PRETTY_NAME: "Ubuntu 24.04.1 LTS"
    NAME: "Ubuntu"
    VERSION_ID: "24.04"
    VERSION: "24.04.1 LTS (Noble Numbat)"
    VERSION_CODENAME: "noble"
    ID: "ubuntu"
    ID_LIKE: "debian"
  OS_KERNEL_VERSION : "Linux katsu 6.8.0-41-generic"    # Expected starting Common Prefix

nic_400g:
  "NIC_400G_FW_VERSION": "234.0.145.0"

pcie_switch:
  cdfp_connected: "no"  # CDFP cable connected: "yes"/"no" (default: "no")
  pcie_details:
    fw_version: "23.02.24.01"

cpld:
  "CPLD_VERSION" : "0x00 0x03 0x00"
  cpld_reg_list:
    - cpld_reg_name: "BOARD_VERSION_TYPE"
      cpld_reg_off: "0x10"
      cpld_reg_exp_val: "0x10"  # Motherboard ID [ID1:ID0]=[0,0] EVT, [ID1:ID0]=[0,1] DVT, [ID1:ID0]=[1,0] PVT
    - cpld_reg_name: "CPLD_MAJOR_VERSION" # This value will be updated after the cpld confirms that the register must be checked.
      cpld_reg_off: "0x11"
      cpld_reg_exp_val: "0x00"
    - cpld_reg_name: "CPLD_MINOR_VERSION"
      cpld_reg_off: "0x12"
      cpld_reg_exp_val: "0x03"
    - cpld_reg_name: "CPLD_MINOR_VERSION"
      cpld_reg_off: "0x13"
      cpld_reg_exp_val: "0x00"

# ------------------- Test BMC Version ---------------------
version_bmc:
  NUM_CPLD_FIELDS: "4"
  CPLD_FIELD_0:
      exp_val: "0"
  CPLD_FIELD_1:
      exp_val: "0"
  CPLD_FIELD_2:
      exp_val: "3"
  CPLD_FIELD_3:
      exp_val: "0"

  BMC_VER: "0.5.0"
  BIOS_VER: "KAT.1.02.01"
  NIC_400G_VER: "235.1.160.0"

  NUM_PCI_SW: "4"
  PCIe_SW_1:
    ver: "23.2.24.1"
  PCIe_SW_2:
    ver: "23.2.24.1"
  PCIe_SW_3:
    ver: "23.2.24.1"
  PCIe_SW_4:
    ver: "23.2.24.1"

# optional settings:
# The configurations below override the internal (test case-specific) YAML files. 
# To override the configuration for a specific test case, uncomment the following lines and update them accordingly

#------------------- Test Compute ---------------------

# ----- Bios info Testcase ------
# bios:
#   BIOS_VENDOR: "American Megatrends International, LLC."

# ----- OS Testcase -------
# os:
#   MANUFACTURER : "CELESTICA-CTH"
#   PRODUCT_NAME : "KATSU MB"
#   SERIAL_NUMBER : "Board-Serial-Number-012345678912"   # Expected starting Common Prefix

# ----- CPU Testcase -------
# cpu:
#   "STREAM_EXECUTABLE_PATH": /usr/local/sbin/stream.exe

#   tlv_details:
#     "BOARD_MANUFACTURER": CELESTICA-CTH
#     "BOARD_MODEL": KATSU MB
#     "BOARD_NAME": Katsu_MB
#     "BOARD_PART_NUMBER": R4122-G0001-01

# ----- DDR Testcase --------
# mem:
#   memtester_script_path: "/usr/local/tools/memtester/"

# ----- PCIe switch Testcase -----
# pcie_switch:
#   switchclid_path: '/usr/sbin/switchclid.x86_64'
#   pcie_details:
#     product_details: "PEX90104 B0"
#     switch_mode: "Managed"

# ------ Stress Testcase ------
# stress:
#   CPU:
#     Stress Time : 600
#   DDR:
#     Stress Time : 600

# ------ CPU sensor check --------
# sensor_cpu:
#   avt_sensors:
#     cpu:
#       cmd: '/usr/local/tools/amdpackage/AVT/AVT_Linux_NDA_2.10.5.3853/AVTCMD -module thermal "getDieTemp()"'
#     dimm:
#       cmd: '/usr/local/tools/amdpackage/AVT/AVT_Linux_NDA_2.10.5.3853/AVTCMD -module pmm "get_pmdata()"'
#     tdp:
#       cmd: '/usr/local/tools/amdpackage/AVT/AVT_Linux_NDA_2.10.5.3853/AVTCMD -module pmm "get_pmdata()"'

# ------ Bandwidth Testcase -------
# bandwidth:
#   CPU:
#     Stress Time : 60
#   DDR:
#     Stress Time : 60

# ------- SecureBoot Testcase -------
# secureboot:
#   "OS_SECURE_BOOT_STATUS": "disabled"
#   "NIC_SECURE_BOOT_STATUS": "Enabled"
#   "PCIE_SW_CLI_PATH": "/usr/sbin/switchclid.x86_64"

# ------------------- Test BMC ---------------------
# version_bmc:
#   NUM_CPLD_FIELDS: "4"
#   CPLD_FIELD_0:
#       name : "Board ver"
#       i2c_bus: "8"
#       addr: "0x65"
#       reg: "0x00"

#   CPLD_FIELD_1:
#       name : "Major ver"
#       i2c_bus: "8"
#       addr: "0x65"
#       reg: "0x01"

#   CPLD_FIELD_2:
#       name : "Minor ver"
#       i2c_bus: "8"
#       addr: "0x65"
#       reg: "0x02"

#   CPLD_FIELD_3:
#       name : "Sub ver"
#       i2c_bus: "8"
#       addr: "0x65"
#       reg: "0x03"

#   BIOS_VER_ATTRIB: "bios_active"

#   NIC_400G_ATTRIB: "PLDM_400GNIC_15"


#   NUM_PCI_SW: "4"
#   PCIe_SW_1:
#     attrib: "PEX_1"
#   PCIe_SW_2:
#     attrib: "PEX_2"
#   PCIe_SW_3:
#     attrib: "PEX_3"
#   PCIe_SW_4:
#     attrib: "PEX_4"
